Integration testing WIP

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -16,6 +16,22 @@ jobs:
       - uses: actions/checkout@v2
       - name: Build
         run: debian/build.sh "aktin-notaufnahme-dwh" "${{ steps.prep.outputs.version }}"
+      - name: Setup Ubuntu for Integration Tests
+        if: ${{ false }}
+        run: |
+          sudo apt-add-repository ppa:ondrej/php --remove
+          sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $osLabel-cran40/" --remove
+          sudo apt update && sudo apt purge -y php-* r-*
+      - name: Setup DWH for Integration Tests
+        if: ${{ false }}
+        run: |
+          wget -qO i2b2.deb "$(curl --silent https://api.github.com/repos/simonkurka/notaufnahme-i2b2/releases/latest | grep -m 1 -E '"browser_download_url": ".*/simonkurka-notaufnahme-i2b2_[0-9]+.[0-9]+.[0-9]+.deb"' | sed -E 's/.*"([^"]+)".*/\1/')"
+          sudo apt install -y ./i2b2.deb ./debian/build/aktin-notaufnahme-dwh_${{ steps.prep.outputs.version }}.deb
+          WAITCOUNT=0
+          while ! curl -f http://localhost/aktin/admin/ >/dev/null 2>&1; do if [ $WAITCOUNT -lt 12 ]; then ((WAITCOUNT++)); echo "Waiting for AKTIN datawarehouse to come up ..."; sleep 5; else echo "AKTIN datawarehouse didn't come up. Aborting ..."; exit 1; fi; done
+      - name: Run Integration Tests
+        if: ${{ false }}
+        run: run-parts --verbose test
       - name: Sign package
         env:
           GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
@@ -47,6 +63,37 @@ jobs:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Build docker image for ${{ github.job }} [httpd]
+        uses: docker/build-push-action@v2
+        with:
+          context: docker/build/httpd
+          tags: |
+            ghcr.io/aktin/notaufnahme-dwh-httpd:latest
+            ghcr.io/aktin/notaufnahme-dwh-httpd:${{ steps.prep.outputs.version }}
+          push: false
+      - name: Build docker image for ${{ github.job }} [database]
+        uses: docker/build-push-action@v2
+        with:
+          context: docker/build/database
+          tags: |
+            ghcr.io/aktin/notaufnahme-dwh-database:latest
+            ghcr.io/aktin/notaufnahme-dwh-database:${{ steps.prep.outputs.version }}
+          push: false
+      - name: Build docker image for ${{ github.job }} [wildfly]
+        uses: docker/build-push-action@v2
+        with:
+          context: docker/build/wildfly
+          tags: |
+            ghcr.io/aktin/notaufnahme-dwh-wildfly:latest
+            ghcr.io/aktin/notaufnahme-dwh-wildfly:${{ steps.prep.outputs.version }}
+          push: false
+      - name: Integration Test on Docker images
+        if: ${{ false }}
+        run: |
+          DWHIMAGENAMESPACE="ghcr.io/aktin/notaufnahme-dwh-" docker-compose -f docker/docker-compose.yaml up --no-build --detach
+          sleep 30
+          run-parts test/
+          DWHIMAGENAMESPACE="ghcr.io/aktin/notaufnahme-dwh-" docker-compose -f docker/docker-compose.yaml down
       - name: Build and push docker image for ${{ github.job }} [httpd]
         uses: docker/build-push-action@v2
         with:
